version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "entamall"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jc7itudm6f2y"
s3_prefix = "entamall"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
